/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Conversation {
  'partnerName' : string,
  'lastMessage' : [] | [string],
  'partnerId' : UserId,
  'unreadCount' : bigint,
  'lastTimestamp' : [] | [Timestamp],
}
export type MatchId = bigint;
export interface MatchResult {
  'createdAt' : Timestamp,
  'user' : UserProfilePublic,
  'youOfferTheyWant' : Array<SkillEntry>,
  'matchId' : MatchId,
  'theyOfferYouWant' : Array<SkillEntry>,
}
export type MessageId = bigint;
export interface MessagePublic {
  'id' : MessageId,
  'content' : string,
  'isRead' : boolean,
  'receiverId' : UserId,
  'timestamp' : Timestamp,
  'senderId' : UserId,
}
export type NotificationId = bigint;
export type NotificationKind = {
    'sessionAccepted' : { 'sessionId' : SessionId }
  } |
  { 'newMatch' : { 'fromUserId' : UserId, 'matchId' : MatchId } } |
  { 'sessionRequest' : { 'fromUserId' : UserId, 'sessionId' : SessionId } } |
  { 'sessionCompleted' : { 'sessionId' : SessionId } } |
  { 'newMessage' : { 'messageId' : MessageId, 'fromUserId' : UserId } } |
  { 'sessionRejected' : { 'sessionId' : SessionId } };
export interface NotificationPublic {
  'id' : NotificationId,
  'kind' : NotificationKind,
  'createdAt' : Timestamp,
  'dismissed' : boolean,
}
export type Proficiency = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'expert' : null };
export interface Review {
  'id' : ReviewId,
  'createdAt' : Timestamp,
  'revieweeId' : UserId,
  'reviewerId' : UserId,
  'comment' : [] | [string],
  'sessionId' : SessionId,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface SaveProfileInput {
  'bio' : string,
  'skillsOffered' : Array<SkillEntry>,
  'name' : string,
  'avatar' : [] | [string],
  'skillsWanted' : Array<SkillEntry>,
}
export type SessionId = bigint;
export interface SessionPublic {
  'id' : SessionId,
  'status' : SessionStatus,
  'topic' : string,
  'createdAt' : Timestamp,
  'receiverId' : UserId,
  'message' : [] | [string],
  'requesterId' : UserId,
  'scheduledAt' : Timestamp,
}
export interface SessionRequest {
  'topic' : string,
  'receiverId' : UserId,
  'message' : [] | [string],
  'scheduledAt' : Timestamp,
}
export type SessionStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'confirmed' : null };
export interface Skill { 'id' : SkillId, 'name' : string }
export interface SkillEntry {
  'skillId' : SkillId,
  'name' : string,
  'proficiency' : Proficiency,
}
export type SkillId = bigint;
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'bio' : string,
  'completedSessions' : bigint,
  'skillsOffered' : Array<SkillEntry>,
  'name' : string,
  'createdAt' : Timestamp,
  'trustScore' : number,
  'avatar' : [] | [string],
  'skillsWanted' : Array<SkillEntry>,
}
export interface _SERVICE {
  'addSkill' : ActorMethod<[string], Skill>,
  'completeSession' : ActorMethod<[SessionId], SessionPublic>,
  'dismissNotification' : ActorMethod<[NotificationId], undefined>,
  'getActiveSessions' : ActorMethod<[], Array<SessionPublic>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getCompletedSessions' : ActorMethod<[], Array<SessionPublic>>,
  'getConversations' : ActorMethod<[], Array<Conversation>>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'completedSessionsCount' : bigint,
      'activeSessionsCount' : bigint,
      'averageTrustScore' : number,
    }
  >,
  'getMatches' : ActorMethod<[], Array<MatchResult>>,
  'getMessages' : ActorMethod<[UserId, [] | [Timestamp]], Array<MessagePublic>>,
  'getNotificationBadgeCount' : ActorMethod<[], bigint>,
  'getNotifications' : ActorMethod<[], Array<NotificationPublic>>,
  'getReceivedReviews' : ActorMethod<[], Array<Review>>,
  'getReviewsForUser' : ActorMethod<[UserId], Array<Review>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  'listSkills' : ActorMethod<[], Array<Skill>>,
  'markMessagesRead' : ActorMethod<[UserId], undefined>,
  'refreshMatches' : ActorMethod<[], Array<MatchResult>>,
  'requestSession' : ActorMethod<[SessionRequest], SessionPublic>,
  'respondToSession' : ActorMethod<[SessionId, boolean], SessionPublic>,
  'saveCallerUserProfile' : ActorMethod<[SaveProfileInput], undefined>,
  'searchSkills' : ActorMethod<[string], Array<Skill>>,
  'sendMessage' : ActorMethod<[UserId, string], MessagePublic>,
  'submitReview' : ActorMethod<[SessionId, bigint, [] | [string]], Review>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];