/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SkillId = IDL.Nat;
export const Skill = IDL.Record({ 'id' : SkillId, 'name' : IDL.Text });
export const SessionId = IDL.Nat;
export const SessionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const SessionPublic = IDL.Record({
  'id' : SessionId,
  'status' : SessionStatus,
  'topic' : IDL.Text,
  'createdAt' : Timestamp,
  'receiverId' : UserId,
  'message' : IDL.Opt(IDL.Text),
  'requesterId' : UserId,
  'scheduledAt' : Timestamp,
});
export const NotificationId = IDL.Nat;
export const Proficiency = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'expert' : IDL.Null,
});
export const SkillEntry = IDL.Record({
  'skillId' : SkillId,
  'name' : IDL.Text,
  'proficiency' : Proficiency,
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'completedSessions' : IDL.Nat,
  'skillsOffered' : IDL.Vec(SkillEntry),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'trustScore' : IDL.Float64,
  'avatar' : IDL.Opt(IDL.Text),
  'skillsWanted' : IDL.Vec(SkillEntry),
});
export const Conversation = IDL.Record({
  'partnerName' : IDL.Text,
  'lastMessage' : IDL.Opt(IDL.Text),
  'partnerId' : UserId,
  'unreadCount' : IDL.Nat,
  'lastTimestamp' : IDL.Opt(Timestamp),
});
export const MatchId = IDL.Nat;
export const MatchResult = IDL.Record({
  'createdAt' : Timestamp,
  'user' : UserProfilePublic,
  'youOfferTheyWant' : IDL.Vec(SkillEntry),
  'matchId' : MatchId,
  'theyOfferYouWant' : IDL.Vec(SkillEntry),
});
export const MessageId = IDL.Nat;
export const MessagePublic = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'isRead' : IDL.Bool,
  'receiverId' : UserId,
  'timestamp' : Timestamp,
  'senderId' : UserId,
});
export const NotificationKind = IDL.Variant({
  'sessionAccepted' : IDL.Record({ 'sessionId' : SessionId }),
  'newMatch' : IDL.Record({ 'fromUserId' : UserId, 'matchId' : MatchId }),
  'sessionRequest' : IDL.Record({
    'fromUserId' : UserId,
    'sessionId' : SessionId,
  }),
  'sessionCompleted' : IDL.Record({ 'sessionId' : SessionId }),
  'newMessage' : IDL.Record({ 'messageId' : MessageId, 'fromUserId' : UserId }),
  'sessionRejected' : IDL.Record({ 'sessionId' : SessionId }),
});
export const NotificationPublic = IDL.Record({
  'id' : NotificationId,
  'kind' : NotificationKind,
  'createdAt' : Timestamp,
  'dismissed' : IDL.Bool,
});
export const ReviewId = IDL.Nat;
export const Review = IDL.Record({
  'id' : ReviewId,
  'createdAt' : Timestamp,
  'revieweeId' : UserId,
  'reviewerId' : UserId,
  'comment' : IDL.Opt(IDL.Text),
  'sessionId' : SessionId,
  'rating' : IDL.Nat,
});
export const SessionRequest = IDL.Record({
  'topic' : IDL.Text,
  'receiverId' : UserId,
  'message' : IDL.Opt(IDL.Text),
  'scheduledAt' : Timestamp,
});
export const SaveProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'skillsOffered' : IDL.Vec(SkillEntry),
  'name' : IDL.Text,
  'avatar' : IDL.Opt(IDL.Text),
  'skillsWanted' : IDL.Vec(SkillEntry),
});

export const idlService = IDL.Service({
  'addSkill' : IDL.Func([IDL.Text], [Skill], []),
  'completeSession' : IDL.Func([SessionId], [SessionPublic], []),
  'dismissNotification' : IDL.Func([NotificationId], [], []),
  'getActiveSessions' : IDL.Func([], [IDL.Vec(SessionPublic)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getCompletedSessions' : IDL.Func([], [IDL.Vec(SessionPublic)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'completedSessionsCount' : IDL.Nat,
          'activeSessionsCount' : IDL.Nat,
          'averageTrustScore' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getMatches' : IDL.Func([], [IDL.Vec(MatchResult)], ['query']),
  'getMessages' : IDL.Func(
      [UserId, IDL.Opt(Timestamp)],
      [IDL.Vec(MessagePublic)],
      ['query'],
    ),
  'getNotificationBadgeCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(NotificationPublic)], ['query']),
  'getReceivedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getReviewsForUser' : IDL.Func([UserId], [IDL.Vec(Review)], ['query']),
  'getUserProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'listSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  'markMessagesRead' : IDL.Func([UserId], [], []),
  'refreshMatches' : IDL.Func([], [IDL.Vec(MatchResult)], []),
  'requestSession' : IDL.Func([SessionRequest], [SessionPublic], []),
  'respondToSession' : IDL.Func([SessionId, IDL.Bool], [SessionPublic], []),
  'saveCallerUserProfile' : IDL.Func([SaveProfileInput], [], []),
  'searchSkills' : IDL.Func([IDL.Text], [IDL.Vec(Skill)], ['query']),
  'sendMessage' : IDL.Func([UserId, IDL.Text], [MessagePublic], []),
  'submitReview' : IDL.Func(
      [SessionId, IDL.Nat, IDL.Opt(IDL.Text)],
      [Review],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SkillId = IDL.Nat;
  const Skill = IDL.Record({ 'id' : SkillId, 'name' : IDL.Text });
  const SessionId = IDL.Nat;
  const SessionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const SessionPublic = IDL.Record({
    'id' : SessionId,
    'status' : SessionStatus,
    'topic' : IDL.Text,
    'createdAt' : Timestamp,
    'receiverId' : UserId,
    'message' : IDL.Opt(IDL.Text),
    'requesterId' : UserId,
    'scheduledAt' : Timestamp,
  });
  const NotificationId = IDL.Nat;
  const Proficiency = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'expert' : IDL.Null,
  });
  const SkillEntry = IDL.Record({
    'skillId' : SkillId,
    'name' : IDL.Text,
    'proficiency' : Proficiency,
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'completedSessions' : IDL.Nat,
    'skillsOffered' : IDL.Vec(SkillEntry),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'trustScore' : IDL.Float64,
    'avatar' : IDL.Opt(IDL.Text),
    'skillsWanted' : IDL.Vec(SkillEntry),
  });
  const Conversation = IDL.Record({
    'partnerName' : IDL.Text,
    'lastMessage' : IDL.Opt(IDL.Text),
    'partnerId' : UserId,
    'unreadCount' : IDL.Nat,
    'lastTimestamp' : IDL.Opt(Timestamp),
  });
  const MatchId = IDL.Nat;
  const MatchResult = IDL.Record({
    'createdAt' : Timestamp,
    'user' : UserProfilePublic,
    'youOfferTheyWant' : IDL.Vec(SkillEntry),
    'matchId' : MatchId,
    'theyOfferYouWant' : IDL.Vec(SkillEntry),
  });
  const MessageId = IDL.Nat;
  const MessagePublic = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'isRead' : IDL.Bool,
    'receiverId' : UserId,
    'timestamp' : Timestamp,
    'senderId' : UserId,
  });
  const NotificationKind = IDL.Variant({
    'sessionAccepted' : IDL.Record({ 'sessionId' : SessionId }),
    'newMatch' : IDL.Record({ 'fromUserId' : UserId, 'matchId' : MatchId }),
    'sessionRequest' : IDL.Record({
      'fromUserId' : UserId,
      'sessionId' : SessionId,
    }),
    'sessionCompleted' : IDL.Record({ 'sessionId' : SessionId }),
    'newMessage' : IDL.Record({
      'messageId' : MessageId,
      'fromUserId' : UserId,
    }),
    'sessionRejected' : IDL.Record({ 'sessionId' : SessionId }),
  });
  const NotificationPublic = IDL.Record({
    'id' : NotificationId,
    'kind' : NotificationKind,
    'createdAt' : Timestamp,
    'dismissed' : IDL.Bool,
  });
  const ReviewId = IDL.Nat;
  const Review = IDL.Record({
    'id' : ReviewId,
    'createdAt' : Timestamp,
    'revieweeId' : UserId,
    'reviewerId' : UserId,
    'comment' : IDL.Opt(IDL.Text),
    'sessionId' : SessionId,
    'rating' : IDL.Nat,
  });
  const SessionRequest = IDL.Record({
    'topic' : IDL.Text,
    'receiverId' : UserId,
    'message' : IDL.Opt(IDL.Text),
    'scheduledAt' : Timestamp,
  });
  const SaveProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'skillsOffered' : IDL.Vec(SkillEntry),
    'name' : IDL.Text,
    'avatar' : IDL.Opt(IDL.Text),
    'skillsWanted' : IDL.Vec(SkillEntry),
  });
  
  return IDL.Service({
    'addSkill' : IDL.Func([IDL.Text], [Skill], []),
    'completeSession' : IDL.Func([SessionId], [SessionPublic], []),
    'dismissNotification' : IDL.Func([NotificationId], [], []),
    'getActiveSessions' : IDL.Func([], [IDL.Vec(SessionPublic)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getCompletedSessions' : IDL.Func([], [IDL.Vec(SessionPublic)], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'completedSessionsCount' : IDL.Nat,
            'activeSessionsCount' : IDL.Nat,
            'averageTrustScore' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getMatches' : IDL.Func([], [IDL.Vec(MatchResult)], ['query']),
    'getMessages' : IDL.Func(
        [UserId, IDL.Opt(Timestamp)],
        [IDL.Vec(MessagePublic)],
        ['query'],
      ),
    'getNotificationBadgeCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(NotificationPublic)], ['query']),
    'getReceivedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getReviewsForUser' : IDL.Func([UserId], [IDL.Vec(Review)], ['query']),
    'getUserProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'listSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
    'markMessagesRead' : IDL.Func([UserId], [], []),
    'refreshMatches' : IDL.Func([], [IDL.Vec(MatchResult)], []),
    'requestSession' : IDL.Func([SessionRequest], [SessionPublic], []),
    'respondToSession' : IDL.Func([SessionId, IDL.Bool], [SessionPublic], []),
    'saveCallerUserProfile' : IDL.Func([SaveProfileInput], [], []),
    'searchSkills' : IDL.Func([IDL.Text], [IDL.Vec(Skill)], ['query']),
    'sendMessage' : IDL.Func([UserId, IDL.Text], [MessagePublic], []),
    'submitReview' : IDL.Func(
        [SessionId, IDL.Nat, IDL.Opt(IDL.Text)],
        [Review],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };