/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SaveProfileInput {
    bio: string;
    skillsOffered: Array<SkillEntry>;
    name: string;
    avatar?: string;
    skillsWanted: Array<SkillEntry>;
}
export interface NotificationPublic {
    id: NotificationId;
    kind: NotificationKind;
    createdAt: Timestamp;
    dismissed: boolean;
}
export type Timestamp = bigint;
export interface MessagePublic {
    id: MessageId;
    content: string;
    isRead: boolean;
    receiverId: UserId;
    timestamp: Timestamp;
    senderId: UserId;
}
export type NotificationKind = {
    __kind__: "sessionAccepted";
    sessionAccepted: {
        sessionId: SessionId;
    };
} | {
    __kind__: "newMatch";
    newMatch: {
        fromUserId: UserId;
        matchId: MatchId;
    };
} | {
    __kind__: "sessionRequest";
    sessionRequest: {
        fromUserId: UserId;
        sessionId: SessionId;
    };
} | {
    __kind__: "sessionCompleted";
    sessionCompleted: {
        sessionId: SessionId;
    };
} | {
    __kind__: "newMessage";
    newMessage: {
        messageId: MessageId;
        fromUserId: UserId;
    };
} | {
    __kind__: "sessionRejected";
    sessionRejected: {
        sessionId: SessionId;
    };
};
export type SkillId = bigint;
export type SessionId = bigint;
export interface SkillEntry {
    skillId: SkillId;
    name: string;
    proficiency: Proficiency;
}
export type MatchId = bigint;
export interface UserProfilePublic {
    id: UserId;
    bio: string;
    completedSessions: bigint;
    skillsOffered: Array<SkillEntry>;
    name: string;
    createdAt: Timestamp;
    trustScore: number;
    avatar?: string;
    skillsWanted: Array<SkillEntry>;
}
export type UserId = Principal;
export interface MatchResult {
    createdAt: Timestamp;
    user: UserProfilePublic;
    youOfferTheyWant: Array<SkillEntry>;
    matchId: MatchId;
    theyOfferYouWant: Array<SkillEntry>;
}
export interface Skill {
    id: SkillId;
    name: string;
}
export type NotificationId = bigint;
export type MessageId = bigint;
export type ReviewId = bigint;
export interface SessionPublic {
    id: SessionId;
    status: SessionStatus;
    topic: string;
    createdAt: Timestamp;
    receiverId: UserId;
    message?: string;
    requesterId: UserId;
    scheduledAt: Timestamp;
}
export interface Conversation {
    partnerName: string;
    lastMessage?: string;
    partnerId: UserId;
    unreadCount: bigint;
    lastTimestamp?: Timestamp;
}
export interface Review {
    id: ReviewId;
    createdAt: Timestamp;
    revieweeId: UserId;
    reviewerId: UserId;
    comment?: string;
    sessionId: SessionId;
    rating: bigint;
}
export interface SessionRequest {
    topic: string;
    receiverId: UserId;
    message?: string;
    scheduledAt: Timestamp;
}
export enum Proficiency {
    intermediate = "intermediate",
    beginner = "beginner",
    expert = "expert"
}
export enum SessionStatus {
    pending = "pending",
    completed = "completed",
    rejected = "rejected",
    confirmed = "confirmed"
}
export interface backendInterface {
    addSkill(name: string): Promise<Skill>;
    completeSession(sessionId: SessionId): Promise<SessionPublic>;
    dismissNotification(notificationId: NotificationId): Promise<void>;
    getActiveSessions(): Promise<Array<SessionPublic>>;
    getCallerUserProfile(): Promise<UserProfilePublic | null>;
    getCompletedSessions(): Promise<Array<SessionPublic>>;
    getConversations(): Promise<Array<Conversation>>;
    getDashboardStats(): Promise<{
        completedSessionsCount: bigint;
        activeSessionsCount: bigint;
        averageTrustScore: number;
    }>;
    getMatches(): Promise<Array<MatchResult>>;
    getMessages(partnerId: UserId, since: Timestamp | null): Promise<Array<MessagePublic>>;
    getNotificationBadgeCount(): Promise<bigint>;
    getNotifications(): Promise<Array<NotificationPublic>>;
    getReceivedReviews(): Promise<Array<Review>>;
    getReviewsForUser(userId: UserId): Promise<Array<Review>>;
    getUserProfile(userId: UserId): Promise<UserProfilePublic | null>;
    listSkills(): Promise<Array<Skill>>;
    markMessagesRead(partnerId: UserId): Promise<void>;
    refreshMatches(): Promise<Array<MatchResult>>;
    requestSession(input: SessionRequest): Promise<SessionPublic>;
    respondToSession(sessionId: SessionId, accept: boolean): Promise<SessionPublic>;
    saveCallerUserProfile(input: SaveProfileInput): Promise<void>;
    searchSkills(searchQuery: string): Promise<Array<Skill>>;
    sendMessage(receiverId: UserId, content: string): Promise<MessagePublic>;
    submitReview(sessionId: SessionId, rating: bigint, comment: string | null): Promise<Review>;
}
import type { Conversation as _Conversation, MatchId as _MatchId, MatchResult as _MatchResult, MessageId as _MessageId, NotificationId as _NotificationId, NotificationKind as _NotificationKind, NotificationPublic as _NotificationPublic, Proficiency as _Proficiency, Review as _Review, ReviewId as _ReviewId, SaveProfileInput as _SaveProfileInput, SessionId as _SessionId, SessionPublic as _SessionPublic, SessionRequest as _SessionRequest, SessionStatus as _SessionStatus, SkillEntry as _SkillEntry, SkillId as _SkillId, Timestamp as _Timestamp, UserId as _UserId, UserProfilePublic as _UserProfilePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addSkill(arg0: string): Promise<Skill> {
        if (this.processError) {
            try {
                const result = await this.actor.addSkill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSkill(arg0);
            return result;
        }
    }
    async completeSession(arg0: SessionId): Promise<SessionPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.completeSession(arg0);
                return from_candid_SessionPublic_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeSession(arg0);
            return from_candid_SessionPublic_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async dismissNotification(arg0: NotificationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissNotification(arg0);
            return result;
        }
    }
    async getActiveSessions(): Promise<Array<SessionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveSessions();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveSessions();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompletedSessions(): Promise<Array<SessionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletedSessions();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletedSessions();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversations(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<{
        completedSessionsCount: bigint;
        activeSessionsCount: bigint;
        averageTrustScore: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getMatches(): Promise<Array<MatchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatches();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatches();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: UserId, arg1: Timestamp | null): Promise<Array<MessagePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0, to_candid_opt_n22(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0, to_candid_opt_n22(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getNotificationBadgeCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationBadgeCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationBadgeCount();
            return result;
        }
    }
    async getNotifications(): Promise<Array<NotificationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceivedReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceivedReviews();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceivedReviews();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewsForUser(arg0: UserId): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsForUser(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsForUser(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSkills(): Promise<Array<Skill>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSkills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSkills();
            return result;
        }
    }
    async markMessagesRead(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessagesRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessagesRead(arg0);
            return result;
        }
    }
    async refreshMatches(): Promise<Array<MatchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshMatches();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshMatches();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestSession(arg0: SessionRequest): Promise<SessionPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.requestSession(to_candid_SessionRequest_n31(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SessionPublic_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestSession(to_candid_SessionRequest_n31(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SessionPublic_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async respondToSession(arg0: SessionId, arg1: boolean): Promise<SessionPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToSession(arg0, arg1);
                return from_candid_SessionPublic_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToSession(arg0, arg1);
            return from_candid_SessionPublic_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: SaveProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_SaveProfileInput_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_SaveProfileInput_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchSkills(arg0: string): Promise<Array<Skill>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchSkills(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchSkills(arg0);
            return result;
        }
    }
    async sendMessage(arg0: UserId, arg1: string): Promise<MessagePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async submitReview(arg0: SessionId, arg1: bigint, arg2: string | null): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, to_candid_opt_n40(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Review_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, to_candid_opt_n40(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Review_n29(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Conversation_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Conversation): Conversation {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_MatchResult_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchResult): MatchResult {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationKind_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationKind): NotificationKind {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationPublic_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationPublic): NotificationPublic {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Proficiency_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Proficiency): Proficiency {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_SessionPublic_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionPublic): SessionPublic {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStatus): SessionStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_SkillEntry_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkillEntry): SkillEntry {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    skillId: _SkillId;
    name: string;
    proficiency: _Proficiency;
}): {
    skillId: SkillId;
    name: string;
    proficiency: Proficiency;
} {
    return {
        skillId: value.skillId,
        name: value.name,
        proficiency: from_candid_Proficiency_n13(_uploadFile, _downloadFile, value.proficiency)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    partnerName: string;
    lastMessage: [] | [string];
    partnerId: _UserId;
    unreadCount: bigint;
    lastTimestamp: [] | [_Timestamp];
}): {
    partnerName: string;
    lastMessage?: string;
    partnerId: UserId;
    unreadCount: bigint;
    lastTimestamp?: Timestamp;
} {
    return {
        partnerName: value.partnerName,
        lastMessage: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.lastMessage)),
        partnerId: value.partnerId,
        unreadCount: value.unreadCount,
        lastTimestamp: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.lastTimestamp))
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SessionId;
    status: _SessionStatus;
    topic: string;
    createdAt: _Timestamp;
    receiverId: _UserId;
    message: [] | [string];
    requesterId: _UserId;
    scheduledAt: _Timestamp;
}): {
    id: SessionId;
    status: SessionStatus;
    topic: string;
    createdAt: Timestamp;
    receiverId: UserId;
    message?: string;
    requesterId: UserId;
    scheduledAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_SessionStatus_n3(_uploadFile, _downloadFile, value.status),
        topic: value.topic,
        createdAt: value.createdAt,
        receiverId: value.receiverId,
        message: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.message)),
        requesterId: value.requesterId,
        scheduledAt: value.scheduledAt
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: _Timestamp;
    user: _UserProfilePublic;
    youOfferTheyWant: Array<_SkillEntry>;
    matchId: _MatchId;
    theyOfferYouWant: Array<_SkillEntry>;
}): {
    createdAt: Timestamp;
    user: UserProfilePublic;
    youOfferTheyWant: Array<SkillEntry>;
    matchId: MatchId;
    theyOfferYouWant: Array<SkillEntry>;
} {
    return {
        createdAt: value.createdAt,
        user: from_candid_UserProfilePublic_n8(_uploadFile, _downloadFile, value.user),
        youOfferTheyWant: from_candid_vec_n10(_uploadFile, _downloadFile, value.youOfferTheyWant),
        matchId: value.matchId,
        theyOfferYouWant: from_candid_vec_n10(_uploadFile, _downloadFile, value.theyOfferYouWant)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    kind: _NotificationKind;
    createdAt: _Timestamp;
    dismissed: boolean;
}): {
    id: NotificationId;
    kind: NotificationKind;
    createdAt: Timestamp;
    dismissed: boolean;
} {
    return {
        id: value.id,
        kind: from_candid_NotificationKind_n26(_uploadFile, _downloadFile, value.kind),
        createdAt: value.createdAt,
        dismissed: value.dismissed
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReviewId;
    createdAt: _Timestamp;
    revieweeId: _UserId;
    reviewerId: _UserId;
    comment: [] | [string];
    sessionId: _SessionId;
    rating: bigint;
}): {
    id: ReviewId;
    createdAt: Timestamp;
    revieweeId: UserId;
    reviewerId: UserId;
    comment?: string;
    sessionId: SessionId;
    rating: bigint;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        revieweeId: value.revieweeId,
        reviewerId: value.reviewerId,
        comment: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.comment)),
        sessionId: value.sessionId,
        rating: value.rating
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: string;
    completedSessions: bigint;
    skillsOffered: Array<_SkillEntry>;
    name: string;
    createdAt: _Timestamp;
    trustScore: number;
    avatar: [] | [string];
    skillsWanted: Array<_SkillEntry>;
}): {
    id: UserId;
    bio: string;
    completedSessions: bigint;
    skillsOffered: Array<SkillEntry>;
    name: string;
    createdAt: Timestamp;
    trustScore: number;
    avatar?: string;
    skillsWanted: Array<SkillEntry>;
} {
    return {
        id: value.id,
        bio: value.bio,
        completedSessions: value.completedSessions,
        skillsOffered: from_candid_vec_n10(_uploadFile, _downloadFile, value.skillsOffered),
        name: value.name,
        createdAt: value.createdAt,
        trustScore: value.trustScore,
        avatar: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.avatar)),
        skillsWanted: from_candid_vec_n10(_uploadFile, _downloadFile, value.skillsWanted)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    expert: null;
}): Proficiency {
    return "intermediate" in value ? Proficiency.intermediate : "beginner" in value ? Proficiency.beginner : "expert" in value ? Proficiency.expert : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sessionAccepted: {
        sessionId: _SessionId;
    };
} | {
    newMatch: {
        fromUserId: _UserId;
        matchId: _MatchId;
    };
} | {
    sessionRequest: {
        fromUserId: _UserId;
        sessionId: _SessionId;
    };
} | {
    sessionCompleted: {
        sessionId: _SessionId;
    };
} | {
    newMessage: {
        messageId: _MessageId;
        fromUserId: _UserId;
    };
} | {
    sessionRejected: {
        sessionId: _SessionId;
    };
}): {
    __kind__: "sessionAccepted";
    sessionAccepted: {
        sessionId: SessionId;
    };
} | {
    __kind__: "newMatch";
    newMatch: {
        fromUserId: UserId;
        matchId: MatchId;
    };
} | {
    __kind__: "sessionRequest";
    sessionRequest: {
        fromUserId: UserId;
        sessionId: SessionId;
    };
} | {
    __kind__: "sessionCompleted";
    sessionCompleted: {
        sessionId: SessionId;
    };
} | {
    __kind__: "newMessage";
    newMessage: {
        messageId: MessageId;
        fromUserId: UserId;
    };
} | {
    __kind__: "sessionRejected";
    sessionRejected: {
        sessionId: SessionId;
    };
} {
    return "sessionAccepted" in value ? {
        __kind__: "sessionAccepted",
        sessionAccepted: value.sessionAccepted
    } : "newMatch" in value ? {
        __kind__: "newMatch",
        newMatch: value.newMatch
    } : "sessionRequest" in value ? {
        __kind__: "sessionRequest",
        sessionRequest: value.sessionRequest
    } : "sessionCompleted" in value ? {
        __kind__: "sessionCompleted",
        sessionCompleted: value.sessionCompleted
    } : "newMessage" in value ? {
        __kind__: "newMessage",
        newMessage: value.newMessage
    } : "sessionRejected" in value ? {
        __kind__: "sessionRejected",
        sessionRejected: value.sessionRejected
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    confirmed: null;
}): SessionStatus {
    return "pending" in value ? SessionStatus.pending : "completed" in value ? SessionStatus.completed : "rejected" in value ? SessionStatus.rejected : "confirmed" in value ? SessionStatus.confirmed : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SkillEntry>): Array<SkillEntry> {
    return value.map((x)=>from_candid_SkillEntry_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Conversation>): Array<Conversation> {
    return value.map((x)=>from_candid_Conversation_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatchResult>): Array<MatchResult> {
    return value.map((x)=>from_candid_MatchResult_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationPublic>): Array<NotificationPublic> {
    return value.map((x)=>from_candid_NotificationPublic_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SessionPublic>): Array<SessionPublic> {
    return value.map((x)=>from_candid_SessionPublic_n1(_uploadFile, _downloadFile, x));
}
function to_candid_Proficiency_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Proficiency): _Proficiency {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_SaveProfileInput_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveProfileInput): _SaveProfileInput {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_SessionRequest_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionRequest): _SessionRequest {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_SkillEntry_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkillEntry): _SkillEntry {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topic: string;
    receiverId: UserId;
    message?: string;
    scheduledAt: Timestamp;
}): {
    topic: string;
    receiverId: _UserId;
    message: [] | [string];
    scheduledAt: _Timestamp;
} {
    return {
        topic: value.topic,
        receiverId: value.receiverId,
        message: value.message ? candid_some(value.message) : candid_none(),
        scheduledAt: value.scheduledAt
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    skillsOffered: Array<SkillEntry>;
    name: string;
    avatar?: string;
    skillsWanted: Array<SkillEntry>;
}): {
    bio: string;
    skillsOffered: Array<_SkillEntry>;
    name: string;
    avatar: [] | [string];
    skillsWanted: Array<_SkillEntry>;
} {
    return {
        bio: value.bio,
        skillsOffered: to_candid_vec_n35(_uploadFile, _downloadFile, value.skillsOffered),
        name: value.name,
        avatar: value.avatar ? candid_some(value.avatar) : candid_none(),
        skillsWanted: to_candid_vec_n35(_uploadFile, _downloadFile, value.skillsWanted)
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    skillId: SkillId;
    name: string;
    proficiency: Proficiency;
}): {
    skillId: _SkillId;
    name: string;
    proficiency: _Proficiency;
} {
    return {
        skillId: value.skillId,
        name: value.name,
        proficiency: to_candid_Proficiency_n38(_uploadFile, _downloadFile, value.proficiency)
    };
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Proficiency): {
    intermediate: null;
} | {
    beginner: null;
} | {
    expert: null;
} {
    return value == Proficiency.intermediate ? {
        intermediate: null
    } : value == Proficiency.beginner ? {
        beginner: null
    } : value == Proficiency.expert ? {
        expert: null
    } : value;
}
function to_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SkillEntry>): Array<_SkillEntry> {
    return value.map((x)=>to_candid_SkillEntry_n36(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
